var adsColl = [
    {
        "bloque": null,
        "dimensions": [[300,250],[320,480],[336,280]],
        "dimensions_mobile": [[300,250],[320,480],[336,280]],
        "dispositivo": "desktop,mobile",
        "id": "gpt_interstitial",
        "id_sitio": 1,
        "islazyload": false,
        "num_segundos_refresh": 30,
        "refresh": false,
        "slotName": "elcomercio/web/post/deportetotal/interstitial",
        "slotName2": "elcomercio/web/post/deportetotal/interstitial",
        "space": "interstitial",
        "url": "elcomercio/post/deportetotal"
    },
    {
        "bloque": "1",
        "dimensions": ['fluid',[728,90],[970,90]],
        "dimensions_mobile": ['fluid',[320,50],[320,60],[320,80]],
        "dispositivo": "desktop,mobile",
        "id": "gpt_top",
        "id_sitio": 1,
        "islazyload": true,
        "num_segundos_refresh": 30,
        "refresh": false,
        "slotName": "elcomercio/web/post/deportetotal/top",
        "slotName2": "elcomercio/web/post/deportetotal/top",
        "space": "top",
        "url": "elcomercio/post/deportetotal"
    },
    {
        "bloque": "1",
        "dimensions": [[1,1]],
        "dimensions_mobile": [],
        "dispositivo": "desktop",
        "id": "gpt_skin",
        "id_sitio": 1,
        "islazyload": false,
        "num_segundos_refresh": 30,
        "refresh": false,
        "slotName": "elcomercio/web/post/deportetotal/skin",
        "slotName2": "elcomercio/web/post/deportetotal/skin",
        "space": "skin",
        "url": "elcomercio/post/deportetotal"
    },
    {
        "bloque": "3",
        "dimensions": [[300,250]],
        "dimensions_mobile": [[300,250],[320,100],[320,50],[300,50],[300,100]],
        "dispositivo": "mobile",
        "id": "gpt_caja3",
        "id_sitio": 1,
        "islazyload": true,
        "num_segundos_refresh": 30,
        "refresh": false,
        "slotName": "elcomercio/web/post/deportetotal/caja3",
        "slotName2": "elcomercio/web/post/deportetotal/caja3",
        "space": "caja3",
        "url": "elcomercio/post/deportetotal"
    },
    {
        "bloque": "1",
        "dimensions": ['fluid',[728,90]],
        "dimensions_mobile": ['fluid',[320,50]],
        "dispositivo": "desktop,mobile",
        "id": "gpt_zocalo",
        "id_sitio": 1,
        "islazyload": false,
        "num_segundos_refresh": 30,
        "refresh": true,
        "slotName": "elcomercio/web/post/deportetotal/zocalo",
        "slotName2": "elcomercio/web/post/deportetotal/zocalo",
        "space": "zocalo",
        "url": "elcomercio/post/deportetotal"
    },
    {
        "bloque": "1",
        "dimensions": ['fluid',[300,250],[300,600]],
        "dimensions_mobile": [],
        "dispositivo": "desktop",
        "id": "gpt_caja1",
        "id_sitio": 1,
        "islazyload": true,
        "num_segundos_refresh": 30,
        "refresh": false,
        "slotName": "elcomercio/web/post/deportetotal/caja1",
        "slotName2": "elcomercio/web/post/deportetotal/caja1",
        "space": "caja1",
        "url": "elcomercio/post/deportetotal"
    },
    {
        "bloque": "4",
        "dimensions": [[300,600],[300,250]],
        "dimensions_mobile": [],
        "dispositivo": "desktop",
        "id": "gpt_caja2",
        "id_sitio": 1,
        "islazyload": true,
        "num_segundos_refresh": 30,
        "refresh": true,
        "slotName": "elcomercio/web/post/deportetotal/caja2",
        "slotName2": "elcomercio/web/post/deportetotal/caja2",
        "space": "caja2",
        "url": "elcomercio/post/deportetotal"
    },
    {
        "bloque": "3",
        "dimensions": [[1,1],[300,250],[300,190]],
        "dimensions_mobile": [[1,1],[300,250],[300,190]],
        "dispositivo": "desktop,mobile",
        "id": "gpt_inline",
        "id_sitio": 1,
        "islazyload": true,
        "num_segundos_refresh": 40,
        "refresh": false,
        "slotName": "elcomercio/web/post/deportetotal/inline",
        "slotName2": "elcomercio/web/post/deportetotal/inline",
        "space": "inline",
        "url": "elcomercio/post/deportetotal"
    },
    {
        "bloque": "2",
        "dimensions": [[1,1]],
        "dimensions_mobile": [[1,1]],
        "dispositivo": "desktop,mobile",
        "id": "gpt_vslider",
        "id_sitio": 1,
        "islazyload": false,
        "num_segundos_refresh": 60,
        "refresh": true,
        "slotName": "elcomercio/web/post/deportetotal/vslider",
        "slotName2": "elcomercio/web/post/deportetotal/vslider",
        "space": "vslider",
        "url": "elcomercio/post/deportetotal"
    },
    {
        "bloque": "3",
        "dimensions": [[300,250]],
        "dimensions_mobile": [[300,250],[320,100],[320,50],[300,100],[300,50]],
        "dispositivo": "mobile",
        "id": "gpt_caja4",
        "id_sitio": 1,
        "islazyload": true,
        "num_segundos_refresh": 30,
        "refresh": false,
        "slotName": "elcomercio/web/post/deportetotal/caja4",
        "slotName2": "elcomercio/web/post/deportetotal/caja4",
        "space": "caja4",
        "url": "elcomercio/post/deportetotal"
    },
    {
        "bloque": "4",
        "dimensions": [[300,250]],
        "dimensions_mobile": [[300,250],[320,100],[320,50],[300,100],[300,50]],
        "dispositivo": "mobile",
        "id": "gpt_caja5",
        "id_sitio": 1,
        "islazyload": true,
        "num_segundos_refresh": 30,
        "refresh": false,
        "slotName": "elcomercio/web/post/deportetotal/caja5",
        "slotName2": "elcomercio/web/post/deportetotal/caja5",
        "space": "caja5",
        "url": "elcomercio/post/deportetotal"
    }
]